# Generated by Django 5.0.6 on 2024-06-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cleitons", "0002_cleiton_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cleiton",
            name="user",
        ),
    ]
