# Generated by Django 5.0.6 on 2024-06-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleitons", "0003_remove_cleiton_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cleiton",
            name="username",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
