# Generated by Django 5.0.6 on 2024-06-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.CharField(max_length=255),
        ),
    ]
